version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
genesis:
  app_state:
    utxo:
      transactionList:
        - version: 1
          txIn: []
          txOut:
            - value: 10000
              pkScript: address1
            - value: 10000
              pkScript: address2
            - value: 10000
              pkScript: address3
            - value: 10000
              pkScript: address4
            - value: 10000
              pkScript: address5
          locktime: 0
      transactionCount: 2