version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
genesis:
  app_state:
    utxo:
      transactionList:
        - version: 1
          txIn: []
          txOut:
            - value: 10000
              pkScript: 618741408250DF80E5BC33999AE29A7E09FEBBD4
            - value: 10000
              pkScript: D864BB8367F7963FE9BA6BC452533C15F1F415FE
            - value: 10000
              pkScript: CC14092F505D1284C8EF287FC97E3E0572591B2D
            - value: 10000
              pkScript: DE1C8C1362C55E076CBEC3855BDC47D8A95CFEC8
            - value: 10000
              pkScript: 2E5E6C36ABDBD3379001E346A834EE56E9E3CD37
          locktime: 0
      transactionCount: 2